### ISSUE TITLE
Why passing GET if only GET is supported?

### ISSUE THREAD

**Issue by petko** [pavlakis/slim-cli#16]
Is there some specific reason why we should pass GET to the command line, when only GET is supported as HTTP request method? Or do you have plans to support more methods in the future?

**Comment by pavlakis** [comment]
Hi @petko 
That was done mainly for transparency. 
To remove it, we will need to use named arguments to allow for defaults.
Happy to look at a PR if you want to contribute.

**Comment by petko** [comment]
I was just curious. As it is already there, I don't think that it will be good idea to remove it now, because it will break backward-compatibility as you said.
