### ISSUE TITLE
use controller in cli

### ISSUE THREAD

**Issue by hotterya** [pavlakis/slim-cli#26]
Hello, I've got controller with action that I want to call in cli, I add to routes `$app->add(new \pavlakis\cli\CliRequest());
` but I can't understand how to call my action, could you please help me? This is my action `Controllers\Api\Token:deleteAction`

**Comment by pavlakis** [comment]
What is your `route`?

As per the docs (adapted for your example)
`php public/index.php /the-delete-route GET param1=value1`

**Comment by hotterya** [comment]
```
 $app->add(new \pavlakis\cli\CliRequest());
 $app->get('/api/v1/token', '\Controllers\Api\Token:getAction');
```
php public/index.php /api/v1/token GET

**Comment by hotterya** [comment]
I've got `PHP Notice:  Undefined index: SERVER_NAME in /app/src/Core/Bootstrap/HttpBootstrap.php on line 78`. I checked there $_SERVER['SERVER_NAME'] and add require setting file for local or server

**Comment by pavlakis** [comment]
Can you confirm the Slim version you are using?
This package currently only supports Slim 3.*

Slim 4 will be supported in v2 which is currently in development.

**Comment by hotterya** [comment]
> Can you confirm the Slim version you are using?
> This package currently only supports Slim 3.*
> 
> Slim 4 will be supported in v2 which is currently in development.

I use Slim 3

**Comment by hotterya** [comment]
I've got two settings files, local.settings.php and server.settings.php, and  I check `strpos($_SERVER['SERVER_NAME'], '.local')` to find out what settings file to use

**Comment by hotterya** [comment]
and even if I just connect my local setting, I've got in terminal

> Command not found

**Comment by pavlakis** [comment]
This sounds like a local setup issue.

This is a middleware package and not a separate command. 

When you call the front controller (e.g. public/index.php) it should behave the same way as when you make a web server request.

For CLI requests, it will create a Mock request and populate it with the parameters you are passing.

**Comment by hotterya** [comment]
So the problem is that It's not  create a Mock request with my param?

**Comment by hotterya** [comment]
Where should I add this ` $app->get('/api/v1/token', '\Controllers\Api\Token:getAction');
` ? In my routes.php after `        $app->add(new \pavlakis\cli\CliRequest());
`?

**Comment by pavlakis** [comment]
Please use this project as reference: https://github.com/phpminds/website/blob/master/app/middleware.php

**Comment by hotterya** [comment]
> Please use this project as reference: https://github.com/phpminds/website/blob/master/app/middleware.php

thanks

**Comment by hotterya** [comment]
I find out why it wasn't work. It works when I use `php public/index.php /token GET` but I need to use `php public/index.php /api/v1/token GET`. Is it possible? I wrote `$app->get('/api/v1/token', '\Controllers\Api\Token:deleteAction');`
