### ISSUE TITLE
Add a little piece of Middleware to test per route if it's CLI

### ISSUE THREAD

**Issue by patricksavalle** [pavlakis/slim-cli#8]
Hi. Maybe add a little middleware that can be added per route. LIke this:

```
require 'Method/Cronjob.php';
$this->get("/cronjob/{period:(?:minute|quarter|hour|day|week|month)}", new Cronjob())
    ->add( new CliRequest() );
```

This is what I built for it:

```
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;

class CliRequest
{
    public function __invoke(ServerRequestInterface $request, ResponseInterface $response, $next)
    {
        if (PHP_SAPI !== 'cli') { 
            return $response->withStatus(404);
        }
        return $next($request, $response);
    }
}
```

**Comment by ckrack** [comment]
You could send this as a PR to the existing code.
Add a method to the existing middleware class, which enables this check.
The method needs to be called when the middleware is added to a route.
Something like `CliRequest::allowOnlyCli()` should work.

**Comment by pavlakis** [comment]
@patricksavalle good point. I'm actually doing that check in my controller/action where I'm using it but you're right, it could be just added as a check in the middleware itself.

As @ckrack suggested, add a PR and unit tests and I can test and add it.

**Comment by patricksavalle** [comment]
What's a PR? :)

**Comment by pavlakis** [comment]
I think that functionality is out of scope. Maybe a different middleware to check the SAPI interface. 
Maybe something like this (not tested)
https://github.com/pavlakis/php-sapi-check-middleware/blob/master/src/Api.php
